apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: spillerom-melding-om-vedtak
  namespace: speilvendt
  labels:
    team: speilvendt
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 3
    replication: 3
    retentionBytes: -1
    retentionHours: -1
    localRetentionHours: 24 # 1 dag lagring p√• rask disk
  acl:
    - team: speilvendt
      application: bakrommet
      access: write
    - team: flex
      application: spinnsyn-backend
      access: read
