name: "Deploy topic"
on:
  push:
    paths:
      - deploy/topics/**
      - .github/workflows/topic.yml
jobs:
  deploy-topic-to-dev:
    if: github.ref_name == 'main'
    name: Deploy topic to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Deploy spillerom-behandlinger topic til dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: deploy/topics/spillerom-behandlinger-topic-dev.yaml
      - name: Deploy spillerom-utbetalinger topic til dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: deploy/topics/sykepenger-spillerom-utbetalinger-topic-dev.yaml
      - name: Deploy spillerom-melding-om-vedtak topic til dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: deploy/topics/spillerom-melding-om-vedtak-topic-dev.yaml
